package com.company.hrms.entity;

import com.company.hrms.enums.Role;
import com.company.hrms.enums.EmployeeStatus;
import com.company.hrms.enums.WorkMode;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "employees")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique employee code (generated by HR system)
    @Column(nullable = false, unique = true)
    private String employeeCode;

    @Column(nullable = false)
    private String firstName;

    private String lastName;

    // Used for login
    @Column(nullable = false, unique = true)
    private String email;

    // Nullable initially (set after email reset)
    private String password;

    // Role: ADMIN, HR, MANAGER, EMPLOYEE
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    private Double salary;

    // ACTIVE, INACTIVE, SUSPENDED
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EmployeeStatus status;

    // Work From Office / Work From Home
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private WorkMode workMode;

    // Account activation flag
    @Column(nullable = false)
    private Boolean enabled = false;

    // Reset token for first-time setup & forgot password
    @Column(unique = true, length = 100)
    private String resetToken;

    // Token expiry time
    private LocalDateTime resetTokenExpiry;

    private LocalDateTime createdAt;

    // ===============================
    // Relationships
    // ===============================

    // Many employees belong to one department
    @ManyToOne
    @JoinColumn(name = "department_id")
    private Department department;

    // Self reference (Manager)
    @ManyToOne
    @JoinColumn(name = "manager_id")
    private Employee manager;

    // One manager -> many subordinates
    @OneToMany(mappedBy = "manager")
    private List<Employee> subordinates;

    // Automatically set createdAt before saving
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
}